name: Mihomo 测速（完整版）

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/0x10240.yml'
  
  schedule:
    - cron: '0 */8 * * *'
  
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  run-speedtest:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4
      
      # 使用 Docker 容器来执行测速任务
      - name: 运行 mihomo-speedtest
        uses: docker://golang:1.21-alpine
        with:
          args: |
            go install github.com/0x10240/mihomo-speedtest@latest
            mihomo-speedtest -c "https://raw.githubusercontent.com/qjlxg/VT/refs/heads/main/clash_config.yaml" \
                             -output 0x10240.yaml \
                             -concurrent 50 \
                             -delay \
                             -timeout 5s
      
      - name: 提交并推送更改
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          git add 0x10240.yaml
          
          if ! git diff --cached --quiet; then
            git commit -m "chore: Update and filter Clash nodes via speedtest"
            git pull --rebase
            git push
          else
            echo "没有节点更改，无需提交。"
          fi
