name: 快速延迟测试

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/latency-test.yml'
  
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  run-latency-test:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 设置 Go 环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: 编译 clash-speedtest 工具
        run: go build -o clash-speedtest-custom

      - name: 运行快速延迟预过滤
        run: |
          ./clash-speedtest-custom -c "https://raw.githubusercontent.com/qjlxg/VT/refs/heads/main/clash_config.yaml" \
                                -output fast-filtered.yaml \
                                

      - name: 提交并推送更改
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add fast-filtered.yaml
          
          if ! git diff --cached --quiet; then
            git commit -m "chore: Update Clash nodes (latency filter)"
            git pull --rebase
            git push
          else
            echo "没有节点更改，无需提交。"
          fi
