name: 完整测速

on:
  push:
    paths:
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  run-full-speed-test:
    runs-on: ubuntu-latest

    steps:
      - name: 检出测速工具仓库
        uses: actions/checkout@v4
        with:
          path: speedtest # 将当前仓库检出到 speedtest 目录

      - name: 设置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache-dependency-path: speedtest/go.sum
          cache: true

      - name: 初始化并编译测速工具
        run: |
          cd speedtest
          go mod init clash-speedtest || true
          go mod tidy
          go build -o clash-speedtest-custom

      - name: 检出目标仓库 (aggregator)
        uses: actions/checkout@v4
        with:
          repository: qjlxg/aggregator
          token: ${{ secrets.AGGREGATOR_PAT }}
          path: aggregator

      - name: 运行完整测速并筛选节点
        run: |
          cd speedtest
          ./clash-speedtest-custom -c "https://raw.githubusercontent.com/qjlxg/VT/refs/heads/main/clash_config.yaml" \
                                   -output ../aggregator/data/clash.yaml \
                                   -min-download-speed 15.8 \
                                   -concurrent 120 \
                                   -rename

      - name: 提交并推送更改到目标仓库
        env:
          GITHUB_TOKEN: ${{ secrets.AGGREGATOR_PAT }}
        run: |
          cd aggregator # 切换到目标仓库目录
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/clash.yaml
          
          if ! git diff --cached --quiet; then
            git commit -m "chore: Update Clash nodes via speedtest"
            
            for i in {1..3}; do
              # 在 URL 中嵌入 token，用于身份验证
              git pull --rebase https://x-access-token:${{ secrets.AGGREGATOR_PAT }}@github.com/qjlxg/aggregator.git
              git push && break
              sleep 5
            done
          else
            echo "没有节点更改，无需提交。"
          fi
