name: XieCang-Speed-Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main
    
jobs:
  speed-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Get subscription URL hash
        id: hash
        run: echo "::set-output name=hash::$(echo "${{ secrets.SUB_URL }}" | shasum -a 256 | head -c 8)"

      - name: Cache speed test results
        id: cache-results
        uses: actions/cache@v3
        with:
          path: speed-test-results.json
          key: ${{ runner.os }}-speed-test-results-${{ steps.hash.outputs.hash }}

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build main.go

      - name: Download subscription
        run: |
          curl -o config.yaml -L "${{ secrets.SUB_URL }}"

      - name: Run speed test
        run: |
          ./main -c config.yaml -output optimized-config.yaml -rename -b 'rate|x1|1x'

      - name: Upload optimized config file
        uses: actions/upload-artifact@v3
        with:
          name: optimized-clash-config
          path: optimized-config.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add optimized-config.yaml speed-test-results.json
          git commit -m "Update optimized Clash config and speed test results" || echo "No changes to commit"
          git push
