name: 下载测速

on:
  push:
    paths:
    - '.github/workflows/xiecang-speed-test.yml'
  
  schedule:
    - cron: '0 */8 * * *'
  # 允许手动触发
  workflow_dispatch:

env:
  
  TZ: Asia/Shanghai

jobs:
  run-speedtest:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4
      
      - name: 设置 Go 环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: 安装 clash-speedtest 工具
        run: |
          go mod init clash-speedtest || true
          go mod tidy
          go build -o clash-speedtest-custom
      
      - name: 运行测速并筛选节点
        run: |
          ./clash-speedtest-custom -c "https://raw.githubusercontent.com/qjlxg/VT/refs/heads/main/clash_config.yaml" \
                                   -output clash.yaml \
                                   -max-latency 808ms \
                                   -min-download-speed 15.8 \
                                   -concurrent 120 \
                                   -rename \
                                   
      - name: 提交并推送更改
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          # 关键改动：使用 git add . 来暂存所有更改
          git add .
          
          if ! git diff --cached --quiet; then
            git commit -m "chore: Update and filter Clash nodes via speedtest"
            
            for i in {1..3}; do
              git pull --rebase
              git push && break
              sleep 5
            done
          else
            echo "没有节点更改，无需提交。"
          fi
